#!/usr/bin/env python3
"""build_gotcha_index.py — the ongoing generator for gotchas/INDEX.md.

Reads every `gotchas/gotcha-*.md` file's frontmatter and Symptom section and
writes one generated file: one line per LIVE entry, symptom plus a link to
its own file — the same content the AGENTS.md gotcha index used to carry by
hand, now generated the way tools/build_todo_index.py generates todo/TODO.md
from todo/*.md. Hand-editing the output fails the check; the gotcha files are
the only place any of this is meant to be edited.

Why this file is not loaded by AGENTS.md's `@` include (practice:
environment-gotchas, revised 2026-09-16): a session pays for every line an
instructions file pulls in before it does any work, and an index of 44+
one-liners is exactly the kind of always-loaded text that grows without
bound as traps accumulate. AGENTS.md now carries a short pointer instead —
search gotchas/ by symptom keyword when a failure looks unexplained — and
this file exists for the deliberate read: browsing the whole catalogue
during a very-deep-check sweep, or when the pointer's grep comes up empty
and a wider look is warranted.

Run:
  python3 tools/build_gotcha_index.py             # write gotchas/INDEX.md
  python3 tools/build_gotcha_index.py --check      # regenerate to memory,
                                                    # diff against the
                                                    # committed file, exit 1
                                                    # on any diff
  python3 tools/build_gotcha_index.py --repo DIR [--check]
      # operate on DIR/gotchas/ instead of this repo's own
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import summary_text  # a symptom is a summary: its links go, see there
import title_case  # practice: headline-capitalization -- applied by tool,
                   # never by hand, on every heading this file generates

# The label every generated file opens with (tools/generated_files.json
# lists them all; Morgan, 2026-09-29): visible as a table on GitHub.
GENERATED_HEADER = (
    '---\n'
    'generated_by: tools/build_gotcha_index.py\n'
    'edit_instead: "gotchas/gotcha-*.md"\n'
    'note: "Generated by tools/build_gotcha_index.py. Don\'t edit here; edit gotchas/gotcha-*.md instead, then run python3 tools/build_gotcha_index.py."\n'
    '---'
)

FM_FIELD_RE = re.compile(r'^([a-z_]+):\s*(.*)$')


class GotchaItem:
    def __init__(self, path, fields, symptom):
        self.path = path
        self.fields = fields
        self.symptom = symptom

    def get(self, key, default=None):
        v = self.fields.get(key)
        if v is None or v == 'null':
            return default
        return v

    @property
    def slug(self):
        return self.get('slug') or self.path.stem


def _unquote(v):
    v = v.strip()
    if v == 'null' or v == '':
        return None
    if v.startswith('"') and v.endswith('"'):
        return v[1:-1].replace('\\"', '"')
    return v


def read_gotcha(path):
    text = path.read_text(encoding='utf-8')
    if not text.startswith('---\n'):
        sys.exit(f'build_gotcha_index FAIL: {path} has no frontmatter fence.')
    end = text.find('\n---', 4)
    if end == -1:
        sys.exit(f'build_gotcha_index FAIL: {path} frontmatter never closes.')
    fm_text = text[4:end]
    fields = {}
    for line in fm_text.splitlines():
        if not line.strip():
            continue
        m = FM_FIELD_RE.match(line)
        if not m:
            continue
        fields[m.group(1)] = _unquote(m.group(2))

    body = text[end:]
    m = re.search(r'^##\s*Symptom\s*\n+(.*?)(?:\n\n|\n##|\Z)', body,
                  re.MULTILINE | re.DOTALL)
    if not m:
        sys.exit(f'build_gotcha_index FAIL: {path} has no ## Symptom section.')
    symptom = summary_text.one_line(m.group(1))
    return GotchaItem(path, fields, symptom)


def load_items(gotchas_dir):
    if not gotchas_dir.exists():
        return []
    return [read_gotcha(p) for p in sorted(gotchas_dir.glob('gotcha-*.md'))]


def render_index_md(items):
    live = [it for it in items if it.get('status', 'live') == 'live']
    live.sort(key=lambda it: it.get('noted') or '')
    lines = [GENERATED_HEADER, '',
             f'# {title_case.title_case("Gotchas — do NOT rediscover these")}',
             '',
             'Full catalogue, one file per trap. AGENTS.md carries only a '
             'pointer to this file and a grep instruction — nothing loads '
             'this list automatically. Open it to browse the whole '
             'catalogue (a very-deep-check sweep, or a grep that came up '
             'empty and a wider look is warranted).',
             '']
    for it in live:
        lines.append(f'- **{it.symptom}** [story]({it.slug}.md)')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def main(argv):
    repo = ROOT
    check = False
    rest = list(argv)
    while rest:
        a = rest.pop(0)
        if a == '--repo':
            repo = pathlib.Path(rest.pop(0)).resolve()
        elif a == '--check':
            check = True
        elif a in ('--help', '-h'):
            print((__doc__ or '').strip())
            return 0
        else:
            sys.exit(f'build_gotcha_index FAIL: unknown argument {a!r}.')

    gotchas_dir = repo / 'gotchas'
    items = load_items(gotchas_dir)
    out_path = gotchas_dir / 'INDEX.md'
    want = render_index_md(items)

    if check:
        have = out_path.read_text(encoding='utf-8') if out_path.exists() else None
        if have != want:
            print(f'build_gotcha_index: DRIFT in {out_path}')
            print('build_gotcha_index: run without --check to regenerate, '
                  'or edit the gotcha files in gotchas/ instead.')
            return 1
        live_n = len([it for it in items if it.get('status', 'live') == 'live'])
        print(f'build_gotcha_index: gotchas/INDEX.md matches, 0 drift, '
              f'{live_n} live entr{"y" if live_n == 1 else "ies"}.')
        return 0

    gotchas_dir.mkdir(parents=True, exist_ok=True)
    out_path.write_text(want, encoding='utf-8')
    live_n = len([it for it in items if it.get('status', 'live') == 'live'])
    print(f'build_gotcha_index: wrote {out_path.relative_to(repo)} from '
          f'{live_n} live entr{"y" if live_n == 1 else "ies"} '
          f'({len(items) - live_n} retired, not listed).')
    return 0


if __name__ == '__main__':
    if any(a in ('--help', '-h') for a in sys.argv[1:]):
        print((__doc__ or '').strip())
        sys.exit(0)
    sys.exit(main(sys.argv[1:]))
